# Generated by Django 3.1.4 on 2021-01-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='Session_key',
            new_name='session_key',
        ),
    ]
